### ISSUE TITLE
Getting error when trying to start openchain-server

### ISSUE THREAD

**Issue by flipsyde606** [openchain/openchain#11]
I followed instructions in doc. Built up the server using docker-compose build, but when I run docker-compose up I get the following error.
P.S. I do have a 'data/config.json' in the openchain folder.

Starting openchain-server*.
Attaching to openchain-server*.
[36mopenchain-server |[0m
[36mopenchain-server |[0m Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'data/config.json' was not found and is not optional. 
[36mopenchain-server |[0m    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload) 
[36mopenchain-server |[0m    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers) 
[36mopenchain-server |[0m    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
[36mopenchain-server |[0m    at Openchain.Server.Startup..ctor(IHostingEnvironment application) 
[36mopenchain-server |[0m --- End of stack trace from previous location where exception was thrown --- 
[36mopenchain-server |[0m    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
[36mopenchain-server |[0m    at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[36mopenchain-server |[0m    at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider services, Type startupType, String environmentName)

**Comment by nekosheen** [comment]
Hey, bit of a thread digging, but did you find a fix for this issue ?

**Comment by AwkwardBen** [comment]
Also seeing this issue, can't currently find a fix.
