### ISSUE TITLE
Error when trying to run Observer mode, missing DLL?

### ISSUE THREAD

**Issue by digitsu** [openchain/openchain#3]
Hi, I'm trying to run an observer on osx, to a validator which is running on a linux machine.

The validator is running fine but when I try to start an observer, I get this error:

```
JC-MacBook-Pro:openchain digitsu$ docker attach openchain-server
info: General[0]
      [2015-12-16 15:53:28Z] Starting Openchain v0.4.4 (DNXCore,Version=v5.0)
info: General[0]
      [2015-12-16 15:53:28Z]
info: General[0]
      [2015-12-16 15:53:28Z] Transaction validation mode disabled (Slave mode)
info: General[0]
      [2015-12-16 15:53:28Z] Current mode: Observer mode
info: General[0]
      [2015-12-16 15:53:28Z] Upstream URL: http://10.0.2.104:8080

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.WebSockets.Client, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
 ---> System.IO.FileNotFoundException: Could not load the specified file.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   --- End of inner exception stack trace ---
   at Openchain.Server.Models.TransactionStreamSubscriber.<Subscribe>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Openchain.Server.Models.TransactionStreamSubscriber.Subscribe(CancellationToken cancel)
   at Openchain.Server.Startup.<Configure>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted
```

**Comment by Flavien** [comment]
Unfortunately, the package we use for WebSockets client is not yet supported on OS X/Linux. It only works on Windows, which means observer mode is currently broken on OS X/Linux.

This is currently being tracked in [this issue](https://github.com/dotnet/corefx/issues/2486), but the ETA is Q1 2016. In the meantime I will try to find a different package that would work cross platform.

**Comment by digitsu** [comment]
Hi Flavien, thanks for the quick response,

Thanks for letting me know.

In the meantime, is there a way to subscribe to the /stream endpoint?
I was trying to run observer just so that I would be able to extract the stream of all updates from a server endpoint.

Cheers

**Comment by Flavien** [comment]
You can use any other programming language (NodeJS, Python, etc.) to connect to the WebSocket endpoint. Each message will be a raw transaction in the order they have been published.

**Comment by Flavien** [comment]
This now works on the latest version (0.7.1).
